mqtt:
  host: [YOUR_MQTT_BROKER_IP]
  user: [USER]
  password: [PASSWORD]

detectors:
  hailo:
    type: hailo
    device: pcief0

# Pi 5 Hardware Acceleration for Video Decoding
ffmpeg:
  hwaccel_args: preset-rpi-5-64

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: bgr

cameras:
  front_yard: # Example Camera
    ffmpeg:
      inputs:
        - path: rtsp://[USER]:[PASS]@[CAMERA_IP]:554/stream
          roles:
            - detect
            - record
    detect:
      enabled: True
    objects:
      track:
        - person
        - car
        - dog

version: 0.14